[FLINK-30880] Update flink version to 1.16.1
apache/flink-connector-jdbc pull request #19
Opened 2023-02-02 11:00 UTC by eskabetxe

2023-02-02 12:04 UTC, zentol commented on .github/workflows/ci.yml
> +          maven-version: 3.8.6
Please dont upgrade maven version beyond 3.8.6 without properly investigating the repercussions of that.

2023-02-02 12:05 UTC, zentol requested changes
You dont need a custom ci.yml. Just modify the link passed in push_pr.yml to the shared workflow.

2023-02-02 13:15 UTC, eskabetxe commented
@zentol its done. I update the branch with another test erroneous..

The version is updated but it will fail again if a new bugfix is released..
Maybe we should change the full url to archive, knowing that it is very slow..
https://archive.apache.org/dist/flink/flink-1.16.1/flink-1.16.1-bin-scala_2.12.tgz

2023-02-03 09:23 UTC, zentol commented
>  Maybe we should change the full url to archive, knowing that it is very slow..

Maybe, yes. The caching in the reusable workflow was broken, but it should work now, so the download speed shouldnt be an issue since it'll only happen once (every few weeks)

2023-02-03 09:23 UTC, zentol approved these changes

2023-02-03 13:39 UTC, merged